include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - '**/*.g.dart'

linter:
  rules:
    - always_use_package_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - use_key_in_widget_constructors
    - avoid_print
    - avoid_void_async
    - avoid_catches_without_on_clauses
    - avoid_slow_async_io
    - avoid_function_literals_in_foreach_calls
    - cascade_invocations
    - cancel_subscriptions
    - close_sinks
    - unawaited_futures
    - unnecessary_await_in_return